# syntax=docker/dockerfile:1

FROM golang:1.21-alpine

# Set the working directory
WORKDIR /app

# Install openssh and any other necessary dependencies
RUN apk add --no-cache openssh

# Expose the application port
EXPOSE 8080

# Command to run the application (with hot reloading if desired)
CMD ["go", "run", "cmd/api/application.go"]
